Namespace Entidades
   Public Class Parametro
      Inherits Entidad

      Public Const NombreTabla As String = "Parametros"

      Public Enum Columnas
         IdEmpresa
         IdParametro
         ValorParametro
         CategoriaParametro
         DescripcionParametro

      End Enum

      Public Enum Parametros
         'Nuevos campos SiSeN categorias
         CargosCalcularPor
         CALIDADUTILIZAMODELOASIGLISTAS
         FORZARLISTADEPRECIOSCLIENTE
         CUITEMPRESA
         SUELDOS_DOMICILIO_EMPRESA
         SUELDOS_CONCEPTO_AGUINALDO
         FACTELECTSINCRONICA
         MODULOFACTURACIONELECTRONICA
         MAILSERVIDOR
         MAILDIRECCION
         MAILUSUARIO
         MAILPASSWORD
         MAILPUERTOSALIDA
         URLWSAA
         CLAVETICKETACCESOFE
         URLWSFE
         URLWSBFE
         UBICACIONPDFSFE 'carpeta donde se van a depositar los PDFs generados para Fact. Electrónica
         NOMBREFANTASIA
         INGRESOSBRUTOS
         FECHAINICIOACTIVIDADES
         TAMAÑOMAXIMOIMAGENES
         FACTURACIONSOLICITACOMPROBANTE
         DIRECCIONWEBEMPRESA
         COMPRASSINPRODUCTOS
         CTACAJAMOVCHEQUES 'Define la cuenta para movimientos de Cheques entre Sucursales
         CLIENTETIENESUCURSALASOC
         RECIBOUTILIZADESCUENTORECARGO
         CATEGORIAFISCALEMPRESA
         MODULOCUENTACORRIENTECLIENTES
         MODULOCAJA
         CTACAJAVENTAS
         CTACAJAVENTASACUMULA
         FACTURACIONMANTIENECLIENTE
         FACTURACIONMANTIENECOMPROBANTE
         CTACAJAPAGO
         RETIENEGANANCIAS
         CTABANCOTRANSFBANCARIA
         CTABANCOACREDTARJETA
         CTABANCOPAGO
         MODULOBANCO
         CTACAJATRANSFBANCARIA
         CTACAJALIQUIDACIONTARJETA
         CALCULOCOMISIONVENDEDOR
         MODULOCONTABILIDAD
         ACTUALIZACOSTOYPRECIOVENTA 'en compras despues de grabar el comprobante pregunta si actualiza los costos y precios de venta
         PRECIOSUNIFICAR
         VENCIMIENTOSISTEMA
         NOMBREEMPRESA
         DIASAVISOVENCIMIENTOSISTEMA
         MODULOFICHAS
         PRODUCTOUTILIZACODIGODEBARRAS
         PRECIOCONIVA
         IMPORTARPRODUCTOSGENERAHISTORIALPRECIOS
         FACTURACIONIGNORARPCDECAJA
         COMPRASIGNORARPCDECAJA
         RECIBOIGNORARPCDECAJA
         PAGOIGNORARPCDECAJA
         FACTURACIONTICKETINCLUYERECARGOGENERAL
         FACTURACIONPRESUPUESTOINCLUYERECARGOGENERAL
         FACTURACIONMUESTRAHISTORIACLINICA
         IDCATEGORIAPACIENTE
         IDCATEGORIADOCTOR
         'COMPRASVALORREDONDEO
         'COMPRASDECIMALESENTOTALES
         'COMPRASDECIMALESENITEMS
         PEDIDOCULTARENTABILIDAD
         PEDIDOSFACTURARAUTOMATICO
         PEDIDOSPROVFACTURARAUTOMATICO
         FACTURACIONINVOCARINVOCADOR
         MODULOCUENTACORRIENTEPROVEEDORES
         CTACAJARECIBOS
         UNIFICALIBROSDEBANCO
         CONTRAMOVIMIENTOENVIORECEPCIONSUCURSAL
         DESCUENTOMAXIMO
         PEDIDOSVISUALIZA
         RETIENEIIBB
         CTACAJADEPOSITOTARJETAS
         CTACAJACOMPRAS
         RECIBOAPLICASALDOENPESOS
         PRODUCTOUTILIZAEMBALAJEARRIBA
         VISUALIZAPAGOAPROVEEDOR
         FACTURACIONREMITOTRANSPUTILIZALOTE
         UTILIZABONOSFISCALESELECTRONICOS
         FACTURACIONPERMITECANTIDADNEGATIVA
         FACTURACIONPERMITECANTIDADNEGATIVAACUMULADA
         DESCRIPCIONADICIONALEMPRESA
         FACTURACIONREMITOTRANSPCALCULABULTOS
         PERMITEPAGOSINAPLICARCOMPROBANTES
         CTACTECLIENTESSEPARAR
         PAGOIMPRIMESALDO
         CTACTECLIENTESPRIORIZARNCSYANTICIPOS
         CAJAMOSTRARNCINDIVIDUAL
         CONSULTARPRECIOSCONEMBALAJE
         CTACTEPROVEEDORESSEPARAR
         FACTURACIONAVISAPRODUCTOSENCERO
         FACTURACIONIGNORARULTIMODIGITOCB
         MAILREQUIERESSL
         MAILREQUIEREAUTENTICACION
         FACTURACIONGRABALIBRONOFUERZACONSFINAL
         PEDIDOSPROVCONPRODUCTOSENCERO
         PEDIDOSESTADOAREMITIR
         MODULOSUELDOS
         CTACTECLIENTESEMISIONPOSTERIOR
         CAJAUTILIZASALDOSDIGITADOS
         DEPOSITOMUESTRACLIENTEXTITULAR
         CAJAPLANILLAMUESTRAPRODUCTOSCONALERTA
         CAJAPLANILLAMUESTRAVENTASENCTACTE
         PRODUCCIONRECETAUNICA
         PRODUCTOUTILIZANOMBRECORTO
         PRODUCTOUTILIZACODIGOLARGO
         PRODUCCIONDESCUENTAPRODFORMULAFACTURAR
         PRODUCCIONDIVIDETAMANO
         CANTIDADCARACTERESPRODUCTOOBSERVACION
         FACTURACIONDECIMALESREDONDEOENPRECIO
         FACTURACIONDECIMALESENPRECIO
         FACTURACIONDECIMALESENTOTALXPRODUCTO
         VisualizarComprobanteVentaAsumeImpresion
         ImpresionMasivaOrdenInverso
         CtaCteProveedoresEmisionPosterior
         CtaCteClientesCalcularPromedios
         ENVIAMAILCLIENTECOMPELECTRONICO
         ModuloExpensas
         EXPENSASPASAJECOMPRASINCLUYEIMPUESTOS
         FACTELECTSOURCE
         FACTELECTDESTINATION
         FACTELECUNIQUEID
         FACTELECSERVICE
         FACTELECTGENERATIONTIME
         FACTELECTEXPIRATIONTIME
         CAJAPERMITIRMOVSINSALDO
         IMPRIMIRLUEGODESOLICITARCAE
         PreciosDecimalesEnVenta
         FACTURACIONTAMANOFUENTEDETALLE
         FACTURACIONSALDOCONTEMPLAHORA
         FACTURACIONMUESTRASALDOCTACTEIMPRESION
         FACTURACIONMARGENDERECHO
         FACTURACIONMARGENIZQUIERDO
         FACTURACIONCLIENTECONTROLADNICF
         FACTURACIONCONTROLATOPECF
         FACTURACIONIMPRIMETICKETNOFISCAL
         MOSTRARNOMBREFANTASIAENCOMPROBANTES
         FACTURACIONPERMITEMODIFICARCLIENTE
         FACTURACIONDIASINVOCACIONCOMPROBANTES
         FACTURACIONDECIMALESREDONDEOENCANTIDAD
         FACTURACIONDECIMALESMOSTRARENCANTIDAD
         COMPRASPERMITEFECHAMAYORHOY
         FACTURACIONPOSICIONNOMBREPRODUCTO


         FACTURACIONMODIFICADESCRECGRALPORC
         FACTURACIONMODIFICADESCRECPRODUCTOPORMONTO
         FACTURACIONPERMITECOBROTARJETAAUTOMATICO
         FACTURACIONTARJETAAUTOMATICO
         FACTURACIONBANCOTARJETAAUTOMATICO
         FACTURACIONRAPIDAMODIFICADESCRECGRALPORC

         FACTURACIONMOSTRARPRECIOCONIVA
         FACTURACIONMOSTRARPRECIOUNITARIO
         FACTURACIONMOSTRARDESC1
         FACTURACIONMOSTRARDESC2
         FACTURACIONMOSTRARKILOS
         FACTURACIONMOSTRARSTOCK

         FACTURACIONRAPIDAMOSTRARDESC1
         FACTURACIONRAPIDAMOSTRARDESC2
         FACTURACIONRAPIDAMOSTRARPRUNITARIO
         FACTURACIONRAPIDAMOSTRARLISTAPRECIO

         CONTROLAEVENTOSDELIMITEDECREDITODECLIENTES

         CAJEROABRIRVARIASVENTANASDEFACTURACION
         CAJEROPERMITEACTUALIZACIONAUTOMATICA
         CAJEROTIEMPODEACTUALIZACIONAUTOMATICA

         CONTABILIDADEJECUTARENLINEA
         CONTABILIDADCUENTAVENTAS
         CONTABILIDADCUENTACOMPRAS
         'CONTABILIDADCUENTAIVA
         RECIBOMUESTRASALDOCTACTEIMPRESION

         INTERESESADICIONALPROPORCIONALDIARIO
         FACTURACIONMUESTRAVENDEDORIMPRESION

         FACTURACIONPRODUCTOMODIFDESCRIPCARGAPRECIOACTUAL

         INTERESESCALCULOCOMPLETOPRIMERPAGO

         INTERESESMONTOAPLICADOINCLUYEINTERESES
         PRODUCTOCODIGONUMERICO
         HABILITACODIGOPRODUCTONUMERICO

         REEMPLAZARCOMPROBANTETIPOCOMPROBANTEORIGEN

         REEMPLAZARCOMPROBANTETIPOCOMPROBANTEDESTINO

         CONTABILIDADCUENTAREDONDEO

         CONTABILIDADREDONDEOIMPORTEMAXIMO

         PRODUCTOCODIGOBARRAPRECIORESPETAETIQUETA

         NOMBREBASEARBA

         NOMBREBASEADJUNTOSCRM

         MODULOLOGISTICA

         CONTABILIDADFORMATOEXPORTACION

         PEDIDOSSOLICITATRANSPORTISTA

         PEDIDOSSOLICITACOMPROBANTEGENERAR

         PEDIDOSPERMITEMODIFICARCLIENTE

         FACTURARPEDIDOSELECCIONADO

         VALIDAEMISORELECTRONICOENRECIBOS

         PREFACTURACONSUMEPEDIDOS

         CONTABILIDADCUENTASECUNDARIAPRODUCTO

         FACTURACIONINFORMEVENTASSI

         CONTABILIDADCUENTASECUNDARIACATEGORIA

         RECIBOPERMITEMODIFICARIMPORTEINTERESES

         FACTURACIONTIPOCOMPROBANTEENVIADOCAJERO

         NDEBCHEQRECHCOM

         FACTURACIONITEMSDETALLACHEQUESYTARJETAS

         FACTURACIONUTILIZAINTERESESTARJETAS

         FACTURACIONTIPOCOMPROBANTEGENERADOCAJERO

         CARGOSEXPENSASFORMAPAGO

         CARGOSEXPENSASTIPOCOMPROBANTE

         CARGOSEXPENSASFECHAFACTURA

         CARGOSEXPENSASPERIODOFACTURA

         CARGOSPERMITEGENERARLIQUIDACIONSINCLIENTES

         RECIBOMONTOMINIMOINTERESPERMITO

         CARGOSGENERARCOMPROBANTEPORITEM

         FACTURACIONENVIOMAILCOPIAOCULTA

         FACTURACIONASUNTOENVIOMASIVOEMAIL

         FACTURACIONCARGARECIBOLUEGONC

         CARGOSPASAJEMOVIMIENTOTOMACOMPROBANTECOMPLETO

         CARGOSUTILIZADESCUENTOSRECARGOS

         URLACTUALIZADOR

         CODIGOCLIENTESINERGIA

         CLAVECLIENTESINERGIA

         IDAPLICACION

         MODULOCARGOS

         FACTURACIONINVOCADOSMANTIENEVENDEDOR

         CTACTEPROVEEDORESDHVISTACONTABLE

         PEDIDOSPERMITEFECHAENTREGADISTINTAS

         VISUALIZASTOCKRESERVADO
         VISUALIZASTOCKDEFECTUOSO
         VISUALIZASTOCKFUTURO
         VISUALIZASTOCKFUTURORESERVADO
         INFDESTOCKMOSTRARPRECIOPREDETERMINADO

         PERMITEABRIRMULTIPLESNOVEDADESNUEVAS

         CANTIDADPADRONESARBA

         FTPSERVIDOR

         FTPUSUARIO

         FTPPASSWORD

         FTPCONEXIONPASIVA

         FTPNOMBREARCHIVO

         FTPFORMATO

         '# Ubicación FTP Movil
         FTPSERVIDORMOVIL
         FTPUSUARIOMOVIL
         FTPPASSWORDMOVIL
         FTPCONEXIONPASIVAMOVIL
         FTPCARPETAREMOTAMOVIL

         FACTURACIONSOLICITANUMERODECOMPROBANTE

         FACTURACIONSOLICITAFORMADEPAGO

         FACTURACIONSOLICITALISTADEPRECIOS

         FACTURACIONCTACTESOLICITADIAFIJO

         SALDOTOMAACTUALALIMPRIMIR

         COMPRASDECIMALESREDONDEOENPRECIO
         COMPRASDECIMALESENPRECIO
         COMPRASDECIMALESENTOTALXPRODUCTO
         COMPRASDECIMALESREDONDEOENCANTIDAD
         COMPRASDECIMALESMOSTRARENCANTIDAD
         COMPRASDECIMALESENTOTALGENERAL

         FACTURACIONDESCUENTOIMPINTIGUALADO

         AFIPHABILITAVENTASPERIODOAUTOMATICAMENTE

         CONFIGURACIONMAIL
         CONFIGURACIONMAILCRM

         SOLICITARCAESELECCIONARTODOS

         VEROBSERVACIONES

         RMACANTIDADMESESHISTORICO
         CRMNOVEDADESOBSERVACIONFACTURABLE
         CRMNOVEDADESPRODUCTOFACTURABLE
         CRMNOVEDADESDIASAVENCERALARMA
         CRMSOLOMUESTRAUSUARIOSACTIVOS
         CRMPERMITEENVIOMAILS

         PEDIDOSESTADOFACTURADO

         CTABANCODEPOSITO

         CTABANCOEXTRACCION

         CTABANCOLIQUIDACIONTARJETA

         CTACAJADEPOSITO

         CTACAJAEXTRACCION

         PEDIDOSUTILIZAORDENCOMPRA

         FACTURACIONDECIMALESENDESCREC

         FACTURACIONVENDEDORENTITULO

         LOTESOLICITAFECHAVENCIMIENTO

         LOTESOLICITADESPACHOIMPORTACION

         UTILIZACENTROCOSTOS

         FACTURACIONSOLICITAVENDEDORALABRIR

         PERMITECAMBIARCENTROCOSTOSCOMPRAS

         PERMITECAMBIARCENTROCOSTOSVENTAS

         PERMITECAMBIARCENTROCOSTOSCAJA

         PERMITECAMBIARCENTROCOSTOSBANCO

         FACTURACIONMANTIENEELCLIENTEDEFAULT

         TIPOIMPRESIONFISCAL

         PERMITECONSULTARMULTIPLESUCURSAL

         CONSULTARMULTIPLESUCURSAL

         FACTURACIONDESCUENTOSAGRUPACANTIDADESPORRUBRO

         CONVERTIRPEDIDOENFACTURACONSERVAPRECIOSPEDIDO

         ACTUALIZARPRECIOSMARCARTODOS

         GENERARPEDIDOSSTOCKSELECCIONATRUE

         GENERAPEDIDOPROVEEDORDESDESTOCKMODIFICAPRECIOCOSTO

         LISTAPRECIOSPREDETERMINADA
         FACTURACIONCAJEROGENERA

         FACTURACIONCAJEROSELECCIONMULTIPLE
         IMPRESIONMUESTRATOTALKILOS

         IMPRESIONMUESTRATOTALPRODUCTOS

         FACTURACIONMODIFICADESCRIPSOLICITAPRECIO

         SOLICITARCAECANTIDADDIASFILTROFECHA

         RECIBOCOMPARTENUMERACIONENTRESUCURSALES

         ORDENARCOBRANZAPOR

         CTACTECLIENTEPINTACUOTA

         FACTURARSINSTOCKCONTROLANOAFECTASTOCK

         PEDIDOSMOSTRARTAMANO
         PEDIDOSMOSTRARUM
         PEDIDOSMOSTRARCOSTO
         PEDIDOSMOSTRARPRECIOVENTAPORTAMANO
         PEDIDOSMOSTRARMONEDA
         FACTURACIONSEMAFOROCALCULOMUESTRA
         PEDIDOSMOSTRARSEMAFORORENTABILIDADDETALLE
         PEDIDOSMOSTRARCRITICIDAD
         PEDIDOSPERMITEMODIFICARDESCREC
         PEDIDOSMUESTRAPROVHABITUAL

         PEDIDOSMOSTRARPRODUCTOESPMM
         PEDIDOSMOSTRARPRODUCTOESPPULGADAS
         PEDIDOSMOSTRARPRODUCTOSAE
         PEDIDOSMOSTRARPRODUCTOPRODUCCIONPROCESO
         PEDIDOSMOSTRARPRODUCTOPRODUCCIONFORMA
         PEDIDOSMOSTRARPRODUCTOLARGOEXTALTO
         PEDIDOSMOSTRARPRODUCTOANCHOINTBASE

         PEDIDOSMONEDAPRECIOVENTAPORTAMANO

         FACTURACIONDECIMALESREDONDEOENTAMANO
         FACTURACIONDECIMALESMOSTRARENTAMANO
         PEDIDOSPERMITEMODIFICARCAMBIO
         PEDIDOSGENPEDPROVOCOBLIGATORIA
         ACTUALIZAPRECIOCOSTOPORTIPOCAMBIO

         VENTASIMPRESIONVISNROSERIE

         CLAVELOTEDESPACHOIMPORTACION

         ACTUALIZARPRECIOSMOSTRARCODIGOPRODUCTOPROVEEDOR

         PEDIDOSURLWEBPOST

         PEDIDOSWEBFORMATO

         ESTADOPEDIDOPENDIENTEWEBPOST

         ESTADOPEDIDOENVIADOWEBPOST

         PEDIDOSURLWEBGET

         PEDIDOSURLWEBPUT

         PEDIDOSMOSTRARURLPLANODETALLE

         FACTURACIONDESCUENTORECARGO2CARGAMANUAL

         PEDIDOSPROVIMPRESIONMUESTRACODIGOPROV

         FACTURACIONPEDIDOSINVOCADOSMANTIENEFORMAPAGO

         FACTURACIONINVOCADOSMANTIENEFORMAPAGO

         ESTADOPRESUPUESTOALANULARPEDIDO

         COMPRASPEDIDOSPROVINVOCADOSMANTIENEFORMAPAGO

         WEBARCHIVOSCLIENTESURLDELETE

         WEBARCHIVOSCLIENTESURLPOST

         WEBARCHIVOSCLIENTESURLGET

         WEBARCHIVOSCLIENTESTAMANOPAGINAPOST

         WEBARCHIVOSPRODUCTOSURLDELETE

         WEBARCHIVOSPRODUCTOSURLGET

         WEBARCHIVOSPRODUCTOSURLPOST

         WEBARCHIVOSPRODUCTOSTAMANOPAGINAPOST

         WEBARCHIVOSPRODSUCURURLDELETE

         WEBARCHIVOSPRODSUCURURLGET

         WEBARCHIVOSPRODSUCURURLPOST

         WEBARCHIVOSPRODSUCURTAMANOPAGINAPOST

         WEBARCHIVOSPRODSUCURPRECIOSURLDELETE

         WEBARCHIVOSPRODSUCURPRECIOSURLGET

         WEBARCHIVOSPRODSUCURPRECIOSURLPOST

         WEBARCHIVOSPRODSUCURPRECIOSTAMANOPAGINAPOST

         WEBARCHIVOSCLIENTESURLGETCOUNT

         WEBARCHIVOSCLIENTESTAMANOPAGINAGET

         WEBARCHIVOSPRODUCTOSURLGETCOUNT

         WEBARCHIVOSPRODUCTOSTAMANOPAGINAGET

         WEBARCHIVOSPRODSUCURURLGETCOUNT

         WEBARCHIVOSPRODSUCURTAMANOPAGINAGET

         WEBARCHIVOSPRODSUCURPRECIOSTAMANOPAGINAGET

         WEBARCHIVOSPRODSUCURPRECIOSURLGETCOUNT

         PEDIDOSMOSTRARFORMULA

         ACTUALIZARPRECIOSEXCEL

         ORDPRODMOSTRARCOSTO

         ORDPRODMOSTRARFORMULA

         ORDPRODMOSTRARPRODUCTOLARGOEXTALTO

         ORDPRODMOSTRARPRODUCTOANCHOINTBASE

         NOMBREBASEPRODUCTOWEB

         CRMMUESTRASOLAPAMASINFO

         PRODUCTOPERMITEESCAMBIABLE

         PRODUCTOPERMITEESBONIFICABLE

         PEDIDOSMOSTRARNOTA

         FTPCARPETASECUNDARIA

         FTPCARPETAREMOTA

         FTPSUBEINFOALSERVIDOR2
         FTPPASSWORD2
         FTPSERVIDOR2
         FTPUSUARIO2
         FTPCARPETAREMOTA2
         FTPCONEXIONPASIVA2

         WEBARCHIVOSCLIENTESURLGETMAXFECHA
         WEBARCHIVOSPRODUCTOSURLGETMAXFECHA
         WEBARCHIVOSPRODSUCURURLGETMAXFECHA
         WEBARCHIVOSPRODSUCURPRECIOSURLGETMAXFECHA

         WEBARCHIVOSLOCALIDADESURLDELETE
         WEBARCHIVOSLOCALIDADESURLGET
         WEBARCHIVOSLOCALIDADESURLGETCOUNT
         WEBARCHIVOSLOCALIDADESURLGETMAXFECHA
         WEBARCHIVOSLOCALIDADESURLPOST
         WEBARCHIVOSLOCALIDADESTAMANOPAGINAPOST
         WEBARCHIVOSLOCALIDADESTAMANOPAGINAGET

         WEBARCHIVOSRUBROSURLDELETE
         WEBARCHIVOSRUBROSURLGET
         WEBARCHIVOSRUBROSURLGETCOUNT
         WEBARCHIVOSRUBROSURLGETMAXFECHA
         WEBARCHIVOSRUBROSURLPOST
         WEBARCHIVOSRUBROSTAMANOPAGINAPOST
         WEBARCHIVOSRUBROSTAMANOPAGINAGET

         WEBARCHIVOSSUBRUBROSURLDELETE
         WEBARCHIVOSSUBRUBROSURLGET
         WEBARCHIVOSSUBRUBROSURLGETCOUNT
         WEBARCHIVOSSUBRUBROSURLGETMAXFECHA
         WEBARCHIVOSSUBRUBROSURLPOST
         WEBARCHIVOSSUBRUBROSTAMANOPAGINAPOST
         WEBARCHIVOSSUBRUBROSTAMANOPAGINAGET

         WEBARCHIVOSSUBSUBRUBROSURLDELETE
         WEBARCHIVOSSUBSUBRUBROSURLGET
         WEBARCHIVOSSUBSUBRUBROSURLGETCOUNT
         WEBARCHIVOSSUBSUBRUBROSURLGETMAXFECHA
         WEBARCHIVOSSUBSUBRUBROSURLPOST
         WEBARCHIVOSSUBSUBRUBROSTAMANOPAGINAPOST
         WEBARCHIVOSSUBSUBRUBROSTAMANOPAGINAGET

         WEBARCHIVOSMARCASURLDELETE
         WEBARCHIVOSMARCASURLGET
         WEBARCHIVOSMARCASURLGETCOUNT
         WEBARCHIVOSMARCASURLGETMAXFECHA
         WEBARCHIVOSMARCASURLPOST
         WEBARCHIVOSMARCASTAMANOPAGINAPOST
         WEBARCHIVOSMARCASTAMANOPAGINAGET
         WEBARCHIVOSMARCASULTIMADESCARGA

         WEBARCHIVOSRUBROSCOMPRASURLDELETE
         WEBARCHIVOSRUBROSCOMPRASURLGET
         WEBARCHIVOSRUBROSCOMPRASURLGETCOUNT
         WEBARCHIVOSRUBROSCOMPRASURLGETMAXFECHA
         WEBARCHIVOSRUBROSCOMPRASURLPOST
         WEBARCHIVOSRUBROSCOMPRASTAMANOPAGINAPOST
         WEBARCHIVOSRUBROSCOMPRASTAMANOPAGINAGET
         WEBARCHIVOSRUBROSCOMPRASULTIMADESCARGA

         WEBARCHIVOSPROVEEDORESURLDELETE
         WEBARCHIVOSPROVEEDORESURLGET
         WEBARCHIVOSPROVEEDORESURLGETCOUNT
         WEBARCHIVOSPROVEEDORESURLGETMAXFECHA
         WEBARCHIVOSPROVEEDORESURLPOST
         WEBARCHIVOSPROVEEDORESTAMANOPAGINAPOST
         WEBARCHIVOSPROVEEDORESTAMANOPAGINAGET
         WEBARCHIVOSPROVEEDORESULTIMADESCARGA

         FACTURACIONSOLICITACAJAALABRIR
         FACTURACIONCAJAENTITULO
         FACTURACIONORDENDETITULO
         FACTURACIONORDENDECOLOR

         ACTUALIZAPRECIOSUTILIZAAJUSTEA

         FACTURACIONRAPIDAMUESTRACOMPROBANTE
         FACTURACIONRAPIDASOLICITAVENDEDORPORDEFECTO
         FACTURACIONRAPIDASOLICITATIPOCOMPROBANTEPORDEFECTO
         VALORPORDEFECTOENRESUMENDEVENTAS

         CANTIDADLINEASDEPRODUCTOAEVALUARPARADESCRECARGO
         PORCENTAJEDEDESCRECARGOPORLINEADEPRODUCTO

         VENTASIMPRESIONMUESTRALOTEOBSERVACION

         EXPORTARVENTASCONFORMATO

         GRABALIBRONOINCLUYERECARGOGENERAL

         WEBARCHIVOSCLIENTESULTIMADESCARGA

         WEBARCHIVOSPRODUCTOSULTIMADESCARGA

         WEBARCHIVOSPRODSUCURULTIMADESCARGA

         WEBARCHIVOSPRODSUCURPRECIOSULTIMADESCARGA

         WEBARCHIVOSLOCALIDADESULTIMADESCARGA

         WEBARCHIVOSRUBROSULTIMADESCARGA

         WEBARCHIVOSSUBRUBROSULTIMADESCARGA

         WEBARCHIVOSSUBSUBRUBROSULTIMADESCARGA

         RECIBOCONCILIAAUTOMATICAMENTETRANSFERENCIAS

         PAGOPROVCONCILIAAUTOMATICAMENTETRANSFERENCIAS

         MACROADHERENTEALINEACION
         MACROADHERENTERELLENADO

         UTILIZASTOCKRESERVADO

         UTILIZASTOCKDEFECTUOSO

         UTILIZASTOCKFUTURO

         UTILIZASTOCKFUTURORESERVADO

         ESTADOPEDIDOPREVINCULACION
         ESTADOPEDIDOPOSTVINCULACION
         ESTADOPEDIDOPROVPREVINCULACION
         ESTADOPEDIDOPROVPOSTVINCULACION

         FACTURACIONRAPIDARECALCULAREFECTIVOALCARGARTARJETA

         NOMBREBASEADJUNTOS

         UBICACIONARCHIVOSPDA

         FICHASACTUALIZAPRECIOSDEVENTA

         FICHASPERMITECAMBIARFORMADEPAGO

         FACTURACIONRAPIDASOLICITACANTIDAD

         SIMOVILCOBRANZAURLBASE

         IMPORTARPEDIDOSFORMATOARCHIVO

         IMPORTARPEDIDOSTIPOCOMPROBANTE

         DIASENTREGAIMPORTACION

         COMPRASTOLERANCIAIVAMANUAL

         SIMOVILCOBRANZATIPODIRECCION

         SIMOVILCOBRANZANOMBRECLIENTE

         CLIENTESCANTIDADVISITASPORDEFECTO

         SIMOVILCOBRANZAINCLUIRCLIENTES

         PEDIDOPROVEEDORESTADONUEVO

         PEDIDOSPROVMUESTRAPROVHABITUAL

         PEDIDOPROVEEDORESTADOAFACTURAR

         PEDIDOPROVEEDORESTADOFACTURADO

         PEDIDOPROVEEDORESTADOANULADO

         PRODUCTOTIENESUBRUBRO
         PRODUCTOTIENESUBSUBRUBRO

         FACTURACIONINVOCARPEDIDOSDEOTRASSUCURSALES

         EMPRESACURRENTUICULTURE

         EXPORTARPRECIOPRODUCTOUSANDOMONEDA

         COMPRASPOSICIONARNOMBREPRODUCTO

         TURNOSTIPOBASE

         TURNOSESTADOBASE

         TURNOSTIPOCAMBIO

         CLIENTEBUSCARPORCODIGOYNRODOCUMENTO

         CLIENTEMOSTRARPRODUCTOSASOCIADOS

         FACTURACIONPERMITEFACTURARENOTRASMONEDAS

         AFIPURLCODIGOQR
         AFIPURLCONTROLARCOMPROBANTE

         ACTUALIZARPRECIOSCALCULO

         ACTUALIZARPRECIOSCALCULODESDECOMPRAS

         REEMPLAZARCOMPROBANTEREAPLICARECIBOS

         FICHASPREGUNTAREEMPLAZARCOMPROBANTE

         PREVENTAIMPRIMIRPEDIDOS

         WEBARCHIVOSPRODUCTOSPUBLICARENWEB

         WEBARCHIVOSPRODUCTOSINCLUIRIMAGENES

         MODULOCONTRATISTAS

         MODULOCONTROLDELICENCIAS

         DEBITOAUTOMATICOSANTANDERCODIGOSERVICIO

         DEBITOAUTOMATICOCUENTABANCARIATRANSBANC

         DEBITOAUTOMATICOCAJACUENTABANCARIATRANSBANC


         DEBITOAUTOMATICOTIPORECIBOCTABANCARIATRANF

         DEBITOAUTOMATICOCOBRADORCTABANCARIATRANF


         PRODUCTOFORMATOLIKEBUSCARPORCODIGO

         SOLICITAMODIFICARFORMULALUEGODELPRODUCTO

         EXPORTARPRECIOSCONIVA

         CLIENTESSUBIRALAWEB

         PRODUCTOSSUBIRALAWEB

         RUBROSSUBIRALAWEB

         MARCASSUBIRALAWEB

         LOCALIDADESSUBIRALAWEB

         PROVEEDORESSUBIRALAWEB

         RUBROSCOMPRASSUBIRALAWEB

         CLIENTESBAJARDELAWEB

         PRODUCTOSBAJARDELAWEB

         RUBROSBAJARDELAWEB

         MARCASBAJARDELAWEB

         LOCALIDADESBAJARDELAWEB

         PROVEEDORESBAJARDELAWEB

         RUBROSCOMPRASBAJARDELAWEB

         CRMMUESTRAREPORTACATEGORIASNOVEDADES

         FACTURACIONCOEFNEGATIVORECUPERAPRECIOULTIMAVENTA

         CRMASUNTOENVIOMASIVONOVEDADESEMAIL

         FICHASIMPRIMECOBROSFORMATORECIBO

         PRODUCTOUTILIZAPRODUCTOWEB

         CRMENVIOMAILCOPIAOCULTA

         PRECIOSPRIORIZACODIGOYDESCRIPCION

         MINUTOSTABLEROCOMANDO

         TURNOSPERMITEFACTURARDESDECALENDARIO

         TURNOSPRODUCTOZONA

         EXPORTARPRODUCTOSDECIMALESREDONDEOENPRECIO

         EXPENSASPERMITECONSINCONCEPTO

         'SIMOVILSUBIDAINCLUIRCLIENTES
         'SIMOVILSUBIDAINCLUIRRUTAS
         SIMOVILSUBIDAINCLUIRCUENTASCORRIENTES
         SIMOVILSUBIDAINCLUIRRUBROS
         SIMOVILSUBIDAINCLUIRPRODUCTOS
         SIMOVILSUBIDAINCLUIRPRODUCTOSPRECIOS
         SIMOVILSUBIDAINCLUIRPRODUCTOSCLIENTES

         SIMOVILPRECIOSCONIVA
         SIMOVILSOLOPRODUCTOSCONSTOCK
         SIMOVILSUBIDAMESESENVIARCUENTASCORRIENTESDEBEHABER

         ACTUALIZARPRECIOSDESDECOMPRASPRIORIZAIVAPRODUCTO

         PEDIDOSMODIFICADESCRIPSOLICITAKILOS

         PEDIDOSMODIFICAPRECIOPRODUCTO

         PEDIDOSDECIMALESMOSTRARLARGOANCHO

         PRODUCTOFORMATOLIKEBUSCARPORNOMBRE

         MODALIDADCOEFICIENTECOBRANZAS

         CRMASUNTOGENERARVERSION

         CRMGENERARVERSIONPARA

         CRMGENERARVERSIONCOPIAOCULTA

         ORIGENCOTIZACIONMONEDA

         'VENTANA APLICACIÓN MOVIL
         CORREOMOVIL1
         CORREOMOVIL2
         CORREOMOVIL3
         BUSQUEDACLIENTES
         ORDENARPRODUCTOS
         SOLICITACIERREPEDIDOS
         USARFECHAEXPORTACION
         OCULTARCOMPARTIRVENTASPORMAIL
         ENVIAMAILCLIENTE
         ENVIAMAILEMPRESA
         OCULTARRESUMENPROMEDIO

         SIMOVILSUBIDAINCLUIRCONFIGURACIONES

         FACTURACIONPERMITECAMBIARCLIENTEVINCULADO

         PRODUCTOBUSQUEDACOMBINACODIGONOMBRE

         BUSCAPRODUCTOPORCODIGOPROVEEDORHABITUAL

         PRODUCTOBUSCARPORCODIGOEXACTO

         EDITAPRODUCTONORMALMODIFICAHISTORIAL

         MONEDAPARACONSULTARPRECIOS

         FACTURACIONSOLICITAVENDEDORPORCLAVE

         FACTURACIONTARJETASVALIDACUPONLOTE

         URLTELEPROM
         FACTURACIONUTILIZAMONEDADOLAR

         FACTURACIONCANTIDADENTEROSENCOTIZACIONDOLAR
         FACTURACIONCANTIDADDECIMALESENCOTIZACIONDOLAR

         SITIENEDESCRECPORCANTIDADIGNORAOTROS

         FACTURACIONDECIMALESGRABARDETALLEENPRECIO

         RUTAARCHIVOSPALM

         LOGISTICAFORMATOEXPORTACIONDEFAULT

         INCLUIRESCAMBIABLEESBONIFICABLE

         SIMOVILSOPORTEURLBASE

         PREVENTAV2RESPETALISTAPRECIOSCLIENTE

         'PREVENTAV2IMPORTADESCUENTOS

         VENCIMIENTOCERTIFICADOFE

         CONSOLIDADOCARGAORDENIDPRODUCTO

         EXPORTARPRECIOSCONIVA1

         ORGANIZARENTREGAFILTRAFECHAENVIO

         ORGANIZARENTREGAPERMITEDISTINTAFECHAENVIO

         REGISTRACIONPAGOSTIPOMOVIMIENTO

         ORGANIZARENTREGASFORMADEPAGO

         COLORCONCILIADO

         COLORNOCONCILIADO

         AFIPCITICOMPRASPRORRATEO

         FACTURACIONASUNTOENVIOMASIVOEMAILCTACTE

         ENVIOMASIVOCOMPROBANTESADJUNTACTACTE

         CTACTECANTDIASVENCICOMPMAIL

         PROCESOSCORREOPRUEBAPARA

         PREVENTAV2IMPORTADESCUENTOSPEDIDOSPDA

         PREVENTAV2IMPORTADESCUENTOSSIMOVILWEB

         EXPENSASPERMITIRCARGARPRODUCTOSSINCONCEPTOS

         OPERACIONCOTIZACIONMONEDAS

         UTILIZAPRECIOCOSTOPORLOTE

         CLIENTEPERMITEMODIFICARCODIGO

         WEBARCHIVOSPRODSUCURACTUALIZASTOCKESTOYACA

         SOLICITATIPOCOMPROBANTE

         SIMOVILSUBIDAINCLUIRCUENTASCORRIENTESDEBEHABER

         PREVENTARESPETAPRECIODELMOVIL

         IMPORTARPEDIDOSALTAPRODUCTOS

         SIMOVILSUBIDAAPLICAPRECIOSOFERTA

         PREVENTAACCIONSINLISTAPRECIOS

         REGISTRACIONPAGOSMODOCONSULTARCOMPROBANTES

         CLIENTEMUESTRACODIGOLETRAS

         SIMOVILPORCMAXDESCUENTO

         SIMOVILPORCMAXRECARGO

         CTACTEPERMITIRMODIFICARCOMPROBANTEASOCIADO

         FACTURACIONIMPRESIONFISCALSINCRONICA
         SIMOVILSUBIDAPAGINARUTAS
         SIMOVILSUBIDAPAGINARUTASCLIENTES
         SIMOVILSUBIDAPAGINARUTASLISTASPRECIOS
         SIMOVILSUBIDAPAGINACLIENTES
         SIMOVILSUBIDAPAGINACUENTASCORRIENTES
         SIMOVILSUBIDAPAGINACUENTASCORRIENTESDEBEHABER
         SIMOVILSUBIDAPAGINARUBROS
         SIMOVILSUBIDAPAGINAPRODUCTOS
         SIMOVILSUBIDAPAGINAPRODUCTOSPRECIOS

         WEBARCHIVOSCARPETAEXPORTACION

         WEBARCHIVOSHABILITARTLS1_1

         WEBARCHIVOSHABILITARTLS1_2

         SIMOVILSUBIDAMAXIMOCUOTASENVIARCUENTASCORRIENTES
         LISTASCONTROLESTADOPENDIENTE
         LISTASCONTROLESTADOENPROCESO
         LISTASCONTROLESTADOTERMINADO
         CALIDADBASEEXTERNACLIENTES
         CALIDADPANELDECONTROLTIEMPOREFRESCO
         CALIDADPANELDECONTROLPLANTATIEMPOPAGINADO

         PRODUCTOUBICACIONPORDEFECTO

         PREVENTAAGRUPAORDENPRODUCTOENCADAPEDIDO

         FACTURACIONRAPIDAMUESTRAFOTOPRODUCTO

         VERSIONDB

         EJECUTABLETAREAPROGRAMADA

         CAJEROIGNORARTIPOCOMPROBANTECLIENTE

         COMPRASSOLICITACOMPRADOR

         ORGANIZARENTREGAFILTROIMPRESO

         ORGANIZARENTREGAFILTROFECHADESDE

         TURISMOCATEGORIAESTABLECIMIENTO
         TURISMOCATEGORIAPASAJEROS
         TURISMOCATEGORIARESPONSABLE
         TURISMORUBROPROGRAMA
         TURISMORUBROVISITA
         TURISMORUBROGASTRONOMIA
         TURISMOFORMULAVISITAS
         TURISMOFORMULAGASTRONOMIA
         TURISMOFORMULAVISITASID
         TURISMOFORMULAGASTRONOMIAID
         TURISMOTIPOCOMPROBANTE
         SIMOVILTURISMOURLBASE
         TURISMOROELAIDCONCEPTO
         TURISMOROELAIDCUENTA
         TURISMOROELAINTERESVTO

         SIMOVILSUBIDAINCLUIRUSUARIOS


         PMCFORMATO

         RECALCULAVALORACIONESESTRELLAS

         ABRIRARCHIVOEXPORTADO

         SIMOVILSOPORTEUSUARIODEFAULT

         UTILIZACUOTASOVENCIMIENTOCCPROVEEDORES

         '----
         TIPODOCUMENTOCLIENTE

         TIPODOCUMENTOPROVEEDOR

         VENTASCONPRODUCTOSENCERO

         FACTURACIONMODIFICANUMEROCOMPROBANTE

         FACTURACIONMODIFICADESCRIPCIONPRODUCTO

         FACTURACIONMODIFICADESCRIPRODCANTIDAD

         FACTURACIONMODDESCACUMULAPRODUCTOS

         FACTURACIONMODIFICADESCRIPSOLICITAKILOS

         FACTURACIONSALDOCTACTEINCLUYECH3ROS

         FACTURACIONMODIFICADESCRECPRODUCTO

         FACTURACIONABRIRCAJACOMPNOFISCAL

         FACTURACIONRAPIDAREEMPLAZARCOMP

         FACTURACIONMODIFICALISTADEPRECIOS

         FACTURACIONINVOCARDEOTROCLIENTE

         FACTURACIONSOLICITAVENDEDOR

         COMPRASMODIFICADESCRIPCIONPRODUCTO
         COMPRASSOLOCARGAPRODUCTOSDELPROVEEDOR

         ACTUALIZAPRECIOSDEVENTA

         FACTURACIONVISUALIZASEMAFOROUTILIDAD
         FACTURACIONVISUALIZACANTIDADCONVERTIDA
         FACTURACIONVISUALIZACONVERSION

         FACTURACIONMODIFICAPRECIOPRODUCTO

         FACTURACIONSELECCIONLOTEMANUAL

         FACTURARSINSTOCK

         FACTURACIONDETALLACHEQUESYTARJETAS

         FACTURACIONCONTADOESENPESOS

         FACTURACIONMUESTRAPROVHABITUAL

         FACTURACIONOFRECECALCULARVUELTO

         RECIBOSOLICITAFECHA

         RECIBOMANTIENENUMMODIFICADA

         VISUALIZARECIBO

         CTACTECATEGORIACLIENTESRECIBO

         PERMITERECIBOSINAPLICARCOMPROBANTES

         IDPRODUCTODESCUENTORECARGO

         CTACTECATEGORIACLIENTE


         WEBARCHIVOSSYNCBASEURL
         WEBARCHIVOSSYNCEXPORTPATH

         WEBARCHIVOSSYNCINCLUIRSUBIDACLIENTES
         WEBARCHIVOSSYNCPAGINASUBIDACLIENTES
         WEBARCHIVOSSYNCINCLUIRDESCARGACLIENTES
         WEBARCHIVOSSYNCPAGINADESCARGACLIENTES

         WEBARCHIVOSSYNCINCLUIRSUBIDALOCALIDADES
         WEBARCHIVOSSYNCPAGINASUBIDALOCALIDADES
         WEBARCHIVOSSYNCINCLUIRDESCARGALOCALIDADES
         WEBARCHIVOSSYNCPAGINADESCARGALOCALIDADES

         WEBARCHIVOSSYNCINCLUIRSUBIDAMARCAS
         WEBARCHIVOSSYNCPAGINASUBIDAMARCAS
         WEBARCHIVOSSYNCINCLUIRDESCARGAMARCAS
         WEBARCHIVOSSYNCPAGINADESCARGAMARCAS

         WEBARCHIVOSSYNCINCLUIRSUBIDAPRODUCTOS
         WEBARCHIVOSSYNCPAGINASUBIDAPRODUCTOS
         WEBARCHIVOSSYNCINCLUIRDESCARGAPRODUCTOS
         WEBARCHIVOSSYNCPAGINADESCARGAPRODUCTOS

         WEBARCHIVOSSYNCINCLUIRSUBIDAPRODUCTOSSUCURSALES
         WEBARCHIVOSSYNCPAGINASUBIDAPRODUCTOSSUCURSALES
         WEBARCHIVOSSYNCINCLUIRDESCARGAPRODUCTOSSUCURSALES
         WEBARCHIVOSSYNCPAGINADESCARGAPRODUCTOSSUCURSALES

         WEBARCHIVOSSYNCINCLUIRSUBIDAPRODSUCPRECIOS
         WEBARCHIVOSSYNCPAGINASUBIDAPRODSUCPRECIOS
         WEBARCHIVOSSYNCINCLUIRDESCARGAPRODSUCPRECIOS
         WEBARCHIVOSSYNCPAGINADESCARGAPRODSUCPRECIOS

         WEBARCHIVOSSYNCINCLUIRSUBIDAPROVEEDORES
         WEBARCHIVOSSYNCPAGINASUBIDAPROVEEDORES
         WEBARCHIVOSSYNCINCLUIRDESCARGAPROVEEDORES
         WEBARCHIVOSSYNCPAGINADESCARGAPROVEEDORES

         WEBARCHIVOSSYNCINCLUIRSUBIDARUBROSCOMPRAS
         WEBARCHIVOSSYNCPAGINASUBIDARUBROSCOMPRAS
         WEBARCHIVOSSYNCINCLUIRDESCARGARUBROSCOMPRAS
         WEBARCHIVOSSYNCPAGINADESCARGARUBROSCOMPRAS

         WEBARCHIVOSSYNCINCLUIRSUBIDARUBROS
         WEBARCHIVOSSYNCPAGINASUBIDARUBROS
         WEBARCHIVOSSYNCINCLUIRDESCARGARUBROS
         WEBARCHIVOSSYNCPAGINADESCARGARUBROS

         WEBARCHIVOSSYNCINCLUIRSUBIDASUBRUBROS
         WEBARCHIVOSSYNCPAGINASUBIDASUBRUBROS
         WEBARCHIVOSSYNCINCLUIRDESCARGASUBRUBROS
         WEBARCHIVOSSYNCPAGINADESCARGASUBRUBROS

         WEBARCHIVOSSYNCINCLUIRSUBIDASUBSUBRUBROS
         WEBARCHIVOSSYNCPAGINASUBIDASUBSUBRUBROS
         WEBARCHIVOSSYNCINCLUIRDESCARGASUBSUBRUBROS
         WEBARCHIVOSSYNCPAGINADESCARGASUBSUBRUBROS

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMCATEGORIAS
         WEBARCHIVOSSYNCPAGINASUBIDACRMCATEGORIAS
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMCATEGORIAS
         WEBARCHIVOSSYNCPAGINADESCARGACRMCATEGORIAS
         WEBARCHIVOSCRMCATEGORIASULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMESTADOS
         WEBARCHIVOSSYNCPAGINASUBIDACRMESTADOS
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMESTADOS
         WEBARCHIVOSSYNCPAGINADESCARGACRMESTADOS
         WEBARCHIVOSCRMESTADOSULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMMEDIOS
         WEBARCHIVOSSYNCPAGINASUBIDACRMMEDIOS
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMMEDIOS
         WEBARCHIVOSSYNCPAGINADESCARGACRMMEDIOS
         WEBARCHIVOSCRMMEDIOSULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMMETODOS
         WEBARCHIVOSSYNCPAGINASUBIDACRMMETODOS
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMMETODOS
         WEBARCHIVOSSYNCPAGINADESCARGACRMMETODOS
         WEBARCHIVOSCRMMETODOSULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMPRIORIDADES
         WEBARCHIVOSSYNCPAGINASUBIDACRMPRIORIDADES
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMPRIORIDADES
         WEBARCHIVOSSYNCPAGINADESCARGACRMPRIORIDADES
         WEBARCHIVOSCRMPRIORIDADESULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMTIPOSCOMENTARIOS
         WEBARCHIVOSSYNCPAGINASUBIDACRMTIPOSCOMENTARIOS
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMTIPOSCOMENTARIOS
         WEBARCHIVOSSYNCPAGINADESCARGACRMTIPOSCOMENTARIOS
         WEBARCHIVOSCRMTIPOSCOMENTARIOSULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMNOVEDADES
         WEBARCHIVOSSYNCPAGINASUBIDACRMNOVEDADES
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMNOVEDADES
         WEBARCHIVOSSYNCPAGINADESCARGACRMNOVEDADES
         WEBARCHIVOSCRMNOVEDADESULTIMADESCARGA

         WEBARCHIVOSSYNCINCLUIRSUBIDACRMNOVEDADESSEG
         WEBARCHIVOSSYNCPAGINASUBIDACRMNOVEDADESSEG
         WEBARCHIVOSSYNCINCLUIRDESCARGACRMNOVEDADESSEG
         WEBARCHIVOSSYNCPAGINADESCARGACRMNOVEDADESSEG
         WEBARCHIVOSCRMNOVEDADESSEGULTIMADESCARGA

         '#########################################
         '#             Tienda Nube               #
         '#########################################
         TIENDANUBEURLBASE
         TIENDANUBELISTAPRECIOS
         TIENDANUBEIDPRODUCTOENVIO
         TIENDANUBECATEGORIACLIENTE
         TIENDANUBECATEGORIAFISCALCLIENTE
         TIENDANUBEVENDEDOR
         TIENDANUBEPEDIDOSTIPOCOMPROBANTE
         TIENDANUBEPEDIDOSFORMADEPAGO
         TIENDANUBEPEDIDOSCRITICIDAD
         TIENDANUBECORREONOTIFICACIONES
         TIENDANUBETOKEN
         '-----------------------------------------

         '#########################################
         '#           Mercado Libre               #
         '#########################################
         MERCADOLIBREURLBASE
         MERCADOLIBRELISTAPRECIOS
         MERCADOLIBREIDPRODUCTOENVIO
         MERCADOLIBRECATEGORIACLIENTE
         MERCADOLIBRECATEGORIAFISCALCLIENTE
         MERCADOLIBREVENDEDOR
         MERCADOLIBREPEDIDOSTIPOCOMPROBANTE
         MERCADOLIBREPEDIDOSFORMADEPAGO
         MERCADOLIBREPEDIDOSCRITICIDAD
         MERCADOLIBRECORREONOTIFICACIONES
         MERCADOLIBRETOKEN
         MERCADOLIBREREFRESHTOKEN
         MERCADOLIBREFECHATOKEN
         MERCADOLIBREIMAGENDEFAULT
         MERCADOLIBRECODIGORESELLER
         MERCADOLIBRECATEGORIADEFAULT
         MERCADOLIBREAPPID
         MERCADOLIBRESECRETKEY
         MERCADOLIBRECAJADEFAULT
         '-----------------------------------------

         '-- REQ-31725.- --
         VENTASPIRELLIURLBASE
         VENTASPIRELLIIDMARCA
         VENTASPIRELLIIDSUCURSAL
         '-----------------
         MODIFICARPRECIOPORDEBAJOPL
         PORCENTAJEPORDEBAJOPL
         MODIFICARPRECIOPORARRIBAPL
         PORCENTAJEPORARRIBAPL

         ENVIAMAILCLIENTERECIBO
         BEJERMANFECHAMODIFICACIONPROVEEDOR
         BEJERMANFECHAMODIFICACIONORDENCOMPRA
         METALSURURLBASEWEBOC

         '        1         2         3         4         5         6         7
         '234567890123456789012345678901234567890123456789012345678901234567890

         SIMOVILGESTIONTURNOSURLBASE

         SIMOVILSUBIDAINCLUIRCALENDARIOS

         SIMOVILSUBIDAINCLUIREMBARCACIONES

         SIMOVILSUBIDAINCLUIRDESTINOS

         SIMOVILTURNOSURLBASE

         LOGINMESESPRESERVARBITACORAERROR

         MESESARCHIVARCRMFINALIZADOS

         MAILCOPIAOCULTACOMPELECTRONICO

         ENVIACOMAILCOMPELECTRONICO

         CONTROLADIASVTODECREDITODECLIENTES

         GENERALESSUBTOTALESENGRILLAS
         RETENCIONESGANANCIASCALCULORECURSIVO
         RETENCIONESGANANCIASCALCULORECURSIVOREPETIR
         COMPRASCONPRODUCTOSENCERO
         CALIDADUTILIZAPAGAUTOMATICOPANELCONTROLPLANTA

         'nuevo PE-31183
         ReservaSemaforoAmarillo
         IDEDICIONAPLICACION
         'PE-30973
         DIASALERTACLIENTESCATEGORIAMODIFICAR

         'PE-31388
         PRODUCTOPUBLICARWEBCARRITO
         PRODUCTOPUBLICARBALANZA
         PRODUCTOPUBLICARLISTAPRECIOCLIENTES
         PRODUCTOPUBLICARAPPGESTION
         PRODUCTOPUBLICARSINCRONIZACIONSUCURSAL
         PRODUCTOPUBLICARAPPEMPRESARIAL

         '-.PE-31623.-
         MUESTRAFECHAACTUALIZA
      End Enum

#Region "Propiedades"

      Public Property IdEmpresa As Integer
      Public Property IdParametro As String
      Public Property DescripcionParametro As String
      Public Property ValorParametro As String
      Public Property CategoriaParametro As String

#End Region

   End Class
End Namespace
