'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSActualiza
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IWSActualizador", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Entidad))>  _
    Partial Public Class WSActualizador
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetVersionCompletaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUltimaVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ActualizarVersionesClientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVersionesClientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SubirScriptsVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EliminarScriptsVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVersionWSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.Actualizador_WSActualiza_WSActualizador
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetVersionCompletaCompleted As GetVersionCompletaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUltimaVersionCompleted As GetUltimaVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event ActualizarVersionesClientesCompleted As ActualizarVersionesClientesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVersionesClientesCompleted As GetVersionesClientesCompletedEventHandler
        
        '''<remarks/>
        Public Event SubirScriptsVersionCompleted As SubirScriptsVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event EliminarScriptsVersionCompleted As EliminarScriptsVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVersionWSCompleted As GetVersionWSCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/GetVersionCompleta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVersionCompleta(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal aplicacion As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal versionInicial As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal versionActual As String, ByVal codigoCliente As Long, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal codigoClienteSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal base As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Versiones
            Dim results() As Object = Me.Invoke("GetVersionCompleta", New Object() {aplicacion, versionInicial, versionActual, codigoCliente, codigoClienteSpecified, password, base})
            Return CType(results(0),Versiones)
        End Function
        
        '''<remarks/>
        Public Function BeginGetVersionCompleta(ByVal aplicacion As String, ByVal versionInicial As String, ByVal versionActual As String, ByVal codigoCliente As Long, ByVal codigoClienteSpecified As Boolean, ByVal password As String, ByVal base As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetVersionCompleta", New Object() {aplicacion, versionInicial, versionActual, codigoCliente, codigoClienteSpecified, password, base}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetVersionCompleta(ByVal asyncResult As System.IAsyncResult) As Versiones
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Versiones)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVersionCompletaAsync(ByVal aplicacion As String, ByVal versionInicial As String, ByVal versionActual As String, ByVal codigoCliente As Long, ByVal codigoClienteSpecified As Boolean, ByVal password As String, ByVal base As String)
            Me.GetVersionCompletaAsync(aplicacion, versionInicial, versionActual, codigoCliente, codigoClienteSpecified, password, base, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVersionCompletaAsync(ByVal aplicacion As String, ByVal versionInicial As String, ByVal versionActual As String, ByVal codigoCliente As Long, ByVal codigoClienteSpecified As Boolean, ByVal password As String, ByVal base As String, ByVal userState As Object)
            If (Me.GetVersionCompletaOperationCompleted Is Nothing) Then
                Me.GetVersionCompletaOperationCompleted = AddressOf Me.OnGetVersionCompletaOperationCompleted
            End If
            Me.InvokeAsync("GetVersionCompleta", New Object() {aplicacion, versionInicial, versionActual, codigoCliente, codigoClienteSpecified, password, base}, Me.GetVersionCompletaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVersionCompletaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVersionCompletaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVersionCompletaCompleted(Me, New GetVersionCompletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/GetUltimaVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUltimaVersion(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal aplicacion As String, ByVal codigoCliente As Long, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal codigoClienteSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal base As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetUltimaVersion", New Object() {aplicacion, codigoCliente, codigoClienteSpecified, password, base})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetUltimaVersion(ByVal aplicacion As String, ByVal codigoCliente As Long, ByVal codigoClienteSpecified As Boolean, ByVal password As String, ByVal base As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUltimaVersion", New Object() {aplicacion, codigoCliente, codigoClienteSpecified, password, base}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetUltimaVersion(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUltimaVersionAsync(ByVal aplicacion As String, ByVal codigoCliente As Long, ByVal codigoClienteSpecified As Boolean, ByVal password As String, ByVal base As String)
            Me.GetUltimaVersionAsync(aplicacion, codigoCliente, codigoClienteSpecified, password, base, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUltimaVersionAsync(ByVal aplicacion As String, ByVal codigoCliente As Long, ByVal codigoClienteSpecified As Boolean, ByVal password As String, ByVal base As String, ByVal userState As Object)
            If (Me.GetUltimaVersionOperationCompleted Is Nothing) Then
                Me.GetUltimaVersionOperationCompleted = AddressOf Me.OnGetUltimaVersionOperationCompleted
            End If
            Me.InvokeAsync("GetUltimaVersion", New Object() {aplicacion, codigoCliente, codigoClienteSpecified, password, base}, Me.GetUltimaVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUltimaVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUltimaVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUltimaVersionCompleted(Me, New GetUltimaVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/ActualizarVersionesClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ActualizarVersionesClientes(<System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")> ByVal versionesClientes() As VersionCliente)
            Me.Invoke("ActualizarVersionesClientes", New Object() {versionesClientes})
        End Sub
        
        '''<remarks/>
        Public Function BeginActualizarVersionesClientes(ByVal versionesClientes() As VersionCliente, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ActualizarVersionesClientes", New Object() {versionesClientes}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndActualizarVersionesClientes(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActualizarVersionesClientesAsync(ByVal versionesClientes() As VersionCliente)
            Me.ActualizarVersionesClientesAsync(versionesClientes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActualizarVersionesClientesAsync(ByVal versionesClientes() As VersionCliente, ByVal userState As Object)
            If (Me.ActualizarVersionesClientesOperationCompleted Is Nothing) Then
                Me.ActualizarVersionesClientesOperationCompleted = AddressOf Me.OnActualizarVersionesClientesOperationCompleted
            End If
            Me.InvokeAsync("ActualizarVersionesClientes", New Object() {versionesClientes}, Me.ActualizarVersionesClientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnActualizarVersionesClientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ActualizarVersionesClientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ActualizarVersionesClientesCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/GetVersionesClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVersionesClientes(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal aplicacion As String, ByVal descargada As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal descargadaSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")> VersionCliente()
            Dim results() As Object = Me.Invoke("GetVersionesClientes", New Object() {aplicacion, descargada, descargadaSpecified})
            Return CType(results(0),VersionCliente())
        End Function
        
        '''<remarks/>
        Public Function BeginGetVersionesClientes(ByVal aplicacion As String, ByVal descargada As Boolean, ByVal descargadaSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetVersionesClientes", New Object() {aplicacion, descargada, descargadaSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetVersionesClientes(ByVal asyncResult As System.IAsyncResult) As VersionCliente()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),VersionCliente())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVersionesClientesAsync(ByVal aplicacion As String, ByVal descargada As Boolean, ByVal descargadaSpecified As Boolean)
            Me.GetVersionesClientesAsync(aplicacion, descargada, descargadaSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVersionesClientesAsync(ByVal aplicacion As String, ByVal descargada As Boolean, ByVal descargadaSpecified As Boolean, ByVal userState As Object)
            If (Me.GetVersionesClientesOperationCompleted Is Nothing) Then
                Me.GetVersionesClientesOperationCompleted = AddressOf Me.OnGetVersionesClientesOperationCompleted
            End If
            Me.InvokeAsync("GetVersionesClientes", New Object() {aplicacion, descargada, descargadaSpecified}, Me.GetVersionesClientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVersionesClientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVersionesClientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVersionesClientesCompleted(Me, New GetVersionesClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/SubirScriptsVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SubirScriptsVersion(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal idAplicacion As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")> ByVal scriptsDeVersion() As VersionScript)
            Me.Invoke("SubirScriptsVersion", New Object() {idAplicacion, scriptsDeVersion})
        End Sub
        
        '''<remarks/>
        Public Function BeginSubirScriptsVersion(ByVal idAplicacion As String, ByVal scriptsDeVersion() As VersionScript, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SubirScriptsVersion", New Object() {idAplicacion, scriptsDeVersion}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndSubirScriptsVersion(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SubirScriptsVersionAsync(ByVal idAplicacion As String, ByVal scriptsDeVersion() As VersionScript)
            Me.SubirScriptsVersionAsync(idAplicacion, scriptsDeVersion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SubirScriptsVersionAsync(ByVal idAplicacion As String, ByVal scriptsDeVersion() As VersionScript, ByVal userState As Object)
            If (Me.SubirScriptsVersionOperationCompleted Is Nothing) Then
                Me.SubirScriptsVersionOperationCompleted = AddressOf Me.OnSubirScriptsVersionOperationCompleted
            End If
            Me.InvokeAsync("SubirScriptsVersion", New Object() {idAplicacion, scriptsDeVersion}, Me.SubirScriptsVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnSubirScriptsVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.SubirScriptsVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SubirScriptsVersionCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/EliminarScriptsVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub EliminarScriptsVersion(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal idAplicacion As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal nroVersion As String)
            Me.Invoke("EliminarScriptsVersion", New Object() {idAplicacion, nroVersion})
        End Sub
        
        '''<remarks/>
        Public Function BeginEliminarScriptsVersion(ByVal idAplicacion As String, ByVal nroVersion As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EliminarScriptsVersion", New Object() {idAplicacion, nroVersion}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndEliminarScriptsVersion(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EliminarScriptsVersionAsync(ByVal idAplicacion As String, ByVal nroVersion As String)
            Me.EliminarScriptsVersionAsync(idAplicacion, nroVersion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EliminarScriptsVersionAsync(ByVal idAplicacion As String, ByVal nroVersion As String, ByVal userState As Object)
            If (Me.EliminarScriptsVersionOperationCompleted Is Nothing) Then
                Me.EliminarScriptsVersionOperationCompleted = AddressOf Me.OnEliminarScriptsVersionOperationCompleted
            End If
            Me.InvokeAsync("EliminarScriptsVersion", New Object() {idAplicacion, nroVersion}, Me.EliminarScriptsVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnEliminarScriptsVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.EliminarScriptsVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EliminarScriptsVersionCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSActualizador/GetVersionWS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVersionWS() As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Version1
            Dim results() As Object = Me.Invoke("GetVersionWS", New Object(-1) {})
            Return CType(results(0),Version1)
        End Function
        
        '''<remarks/>
        Public Function BeginGetVersionWS(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetVersionWS", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetVersionWS(ByVal asyncResult As System.IAsyncResult) As Version1
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Version1)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVersionWSAsync()
            Me.GetVersionWSAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVersionWSAsync(ByVal userState As Object)
            If (Me.GetVersionWSOperationCompleted Is Nothing) Then
                Me.GetVersionWSOperationCompleted = AddressOf Me.OnGetVersionWSOperationCompleted
            End If
            Me.InvokeAsync("GetVersionWS", New Object(-1) {}, Me.GetVersionWSOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVersionWSOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVersionWSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVersionWSCompleted(Me, New GetVersionWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class Versiones
        
        Private listadoVersionesField() As Version
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property ListadoVersiones() As Version()
            Get
                Return Me.listadoVersionesField
            End Get
            Set
                Me.listadoVersionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class Version
        
        Private nroVersionField As String
        
        Private scriptsField As Scripts
        
        Private uRLMSIField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NroVersion() As String
            Get
                Return Me.nroVersionField
            End Get
            Set
                Me.nroVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Scripts() As Scripts
            Get
                Return Me.scriptsField
            End Get
            Set
                Me.scriptsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property URLMSI() As String
            Get
                Return Me.uRLMSIField
            End Get
            Set
                Me.uRLMSIField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class Scripts
        
        Private itemsField() As VersionScript
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Items() As VersionScript()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class VersionScript
        Inherits Entidad
        
        Private aplicacionField As Aplicacion
        
        Private clienteField As Cliente
        
        Private nombreField As String
        
        Private nroVersionField As String
        
        Private obligatorioField As Boolean
        
        Private obligatorioFieldSpecified As Boolean
        
        Private ordenField As Integer
        
        Private ordenFieldSpecified As Boolean
        
        Private scriptField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Aplicacion() As Aplicacion
            Get
                Return Me.aplicacionField
            End Get
            Set
                Me.aplicacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Cliente() As Cliente
            Get
                Return Me.clienteField
            End Get
            Set
                Me.clienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NroVersion() As String
            Get
                Return Me.nroVersionField
            End Get
            Set
                Me.nroVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Obligatorio() As Boolean
            Get
                Return Me.obligatorioField
            End Get
            Set
                Me.obligatorioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ObligatorioSpecified() As Boolean
            Get
                Return Me.obligatorioFieldSpecified
            End Get
            Set
                Me.obligatorioFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Orden() As Integer
            Get
                Return Me.ordenField
            End Get
            Set
                Me.ordenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OrdenSpecified() As Boolean
            Get
                Return Me.ordenFieldSpecified
            End Get
            Set
                Me.ordenFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Script() As String
            Get
                Return Me.scriptField
            End Get
            Set
                Me.scriptField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class Aplicacion
        Inherits Entidad
        
        Private idAplicacionField As String
        
        Private nombreAplicacionField As String
        
        Private nombreMSIField As String
        
        Private pathMSIField As String
        
        Private pathScriptsField As String
        
        Private uRLServerField As String
        
        Private ultimaVersionField As Version1
        
        Private versionesField() As Version2
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdAplicacion() As String
            Get
                Return Me.idAplicacionField
            End Get
            Set
                Me.idAplicacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NombreAplicacion() As String
            Get
                Return Me.nombreAplicacionField
            End Get
            Set
                Me.nombreAplicacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NombreMSI() As String
            Get
                Return Me.nombreMSIField
            End Get
            Set
                Me.nombreMSIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PathMSI() As String
            Get
                Return Me.pathMSIField
            End Get
            Set
                Me.pathMSIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PathScripts() As String
            Get
                Return Me.pathScriptsField
            End Get
            Set
                Me.pathScriptsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property URLServer() As String
            Get
                Return Me.uRLServerField
            End Get
            Set
                Me.uRLServerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UltimaVersion() As Version1
            Get
                Return Me.ultimaVersionField
            End Get
            Set
                Me.ultimaVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.XMLs")>  _
        Public Property Versiones() As Version2()
            Get
                Return Me.versionesField
            End Get
            Set
                Me.versionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="Version", [Namespace]:="http://schemas.datacontract.org/2004/07/System")>  _
    Partial Public Class Version1
        
        Private _BuildField As Integer
        
        Private _MajorField As Integer
        
        Private _MinorField As Integer
        
        Private _RevisionField As Integer
        
        '''<remarks/>
        Public Property _Build() As Integer
            Get
                Return Me._BuildField
            End Get
            Set
                Me._BuildField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property _Major() As Integer
            Get
                Return Me._MajorField
            End Get
            Set
                Me._MajorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property _Minor() As Integer
            Get
                Return Me._MinorField
            End Get
            Set
                Me._MinorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property _Revision() As Integer
            Get
                Return Me._RevisionField
            End Get
            Set
                Me._RevisionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="Version", [Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.XMLs")>  _
    Partial Public Class Version2
        
        Private comentarioField As String
        
        Private fechaField As Date
        
        Private fechaFieldSpecified As Boolean
        
        Private versionField As Version1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Comentario() As String
            Get
                Return Me.comentarioField
            End Get
            Set
                Me.comentarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaSpecified() As Boolean
            Get
                Return Me.fechaFieldSpecified
            End Get
            Set
                Me.fechaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Version() As Version1
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(VersionCliente)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Cliente)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Aplicacion)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(VersionScript)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class Entidad
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class VersionCliente
        Inherits Entidad
        
        Private aplicacionField As Aplicacion
        
        Private clienteField As Cliente
        
        Private descargadaField As Boolean
        
        Private descargadaFieldSpecified As Boolean
        
        Private nombreBaseField As String
        
        Private nroVersionHabilitadaField As String
        
        Private permiteActualizarField As Boolean
        
        Private permiteActualizarFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Aplicacion() As Aplicacion
            Get
                Return Me.aplicacionField
            End Get
            Set
                Me.aplicacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Cliente() As Cliente
            Get
                Return Me.clienteField
            End Get
            Set
                Me.clienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descargada() As Boolean
            Get
                Return Me.descargadaField
            End Get
            Set
                Me.descargadaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DescargadaSpecified() As Boolean
            Get
                Return Me.descargadaFieldSpecified
            End Get
            Set
                Me.descargadaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NombreBase() As String
            Get
                Return Me.nombreBaseField
            End Get
            Set
                Me.nombreBaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NroVersionHabilitada() As String
            Get
                Return Me.nroVersionHabilitadaField
            End Get
            Set
                Me.nroVersionHabilitadaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PermiteActualizar() As Boolean
            Get
                Return Me.permiteActualizarField
            End Get
            Set
                Me.permiteActualizarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PermiteActualizarSpecified() As Boolean
            Get
                Return Me.permiteActualizarFieldSpecified
            End Get
            Set
                Me.permiteActualizarFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Eniac.ServerActualizar.Entidades")>  _
    Partial Public Class Cliente
        Inherits Entidad
        
        Private claveClienteField As String
        
        Private codigoClienteField As Long
        
        Private codigoClienteFieldSpecified As Boolean
        
        Private nombreClienteField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ClaveCliente() As String
            Get
                Return Me.claveClienteField
            End Get
            Set
                Me.claveClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoCliente() As Long
            Get
                Return Me.codigoClienteField
            End Get
            Set
                Me.codigoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CodigoClienteSpecified() As Boolean
            Get
                Return Me.codigoClienteFieldSpecified
            End Get
            Set
                Me.codigoClienteFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                Me.nombreClienteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetVersionCompletaCompletedEventHandler(ByVal sender As Object, ByVal e As GetVersionCompletaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVersionCompletaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Versiones
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Versiones)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetUltimaVersionCompletedEventHandler(ByVal sender As Object, ByVal e As GetUltimaVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUltimaVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ActualizarVersionesClientesCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetVersionesClientesCompletedEventHandler(ByVal sender As Object, ByVal e As GetVersionesClientesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVersionesClientesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VersionCliente()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VersionCliente())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub SubirScriptsVersionCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub EliminarScriptsVersionCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetVersionWSCompletedEventHandler(ByVal sender As Object, ByVal e As GetVersionWSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVersionWSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Version1
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Version1)
            End Get
        End Property
    End Class
End Namespace
